echo delete frontend deployment and service...
kubectl -n mtdrworkshop delete deployment todolistapp-springboot-deployment --ignore-not-found || echo "⚠️ Deployment no encontrado"
kubectl -n mtdrworkshop delete service todolistapp-springboot-service --ignore-not-found || echo "⚠️ Service no encontrado"
