import { User } from "../../../../../../interfaces/user";

export const employeeTestData: User[] = [
  {
    userId: 1,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    role: "frontend",
    workModality: "Full-time",
    telegramId: "@alicejohnson",
    phoneNumber: "+1234567890",
    creationDate: "2025-01-10T08:30:00Z",
    teamId: 101,
  },
  {
    userId: 2,
    name: "Carlos Méndez",
    email: "carlos.mendez@example.com",
    role: "manager",
    workModality: "Part-time",
    telegramId: "@carlosm",
    phoneNumber: "+1234567891",
    creationDate: "2025-02-12T10:00:00Z",
    teamId: 101,
  },
  {
    userId: 3,
    name: "Fatima Al-Hassan",
    email: "fatima.hassan@example.com",
    role: "designer",
    workModality: "Full-time",
    telegramId: "@fatimaUX",
    phoneNumber: "+1234567892",
    creationDate: "2025-02-15T11:45:00Z",
    teamId: 102,
  },
  {
    userId: 4,
    name: "Jun Park",
    email: "jun.park@example.com",
    role: "data",
    workModality: "Part-time",
    telegramId: "@junpark",
    phoneNumber: "+1234567893",
    creationDate: "2025-03-01T09:15:00Z",
    teamId: 103,
  },
  {
    userId: 5,
    name: "Lina Dobrev",
    email: "lina.dobrev@example.com",
    role: "qa",
    workModality: "Full-time",
    telegramId: "@linaQA",
    phoneNumber: "+1234567894",
    creationDate: "2025-03-05T14:00:00Z",
    teamId: 104,
  },
];
