name: Deployment Workflow

# This workflow is currently disabled
# It will be used for deployment to production in the future

on:
  # Disabled - will be enabled when deployment flow is ready
  # push:
  #   branches: [ main ]
  #   paths:
  #     - 'MainProject/MtdrSpring/backend/src/main/java/com/springboot/MyTodoList/**'
  #     - 'MainProject/MtdrSpring/backend/src/main/frontend/**'
  
  # Allow manual triggers for testing
  workflow_dispatch:

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Placeholder for future deployment steps
        run: echo "Deployment workflow is currently disabled. This is a placeholder for future implementation." 