name: Pull Request Labeler

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'MainProject/MtdrSpring/backend/src/main/java/com/springboot/MyTodoList/**'
      - 'MainProject/MtdrSpring/backend/src/main/frontend/**'

# Permissions needed for the labeler to function properly
permissions:
  pull-requests: write
  contents: read

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml 