name: Pull Request Labeler

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'MainProject/MtdrSpring/backend/src/main/java/com/springboot/MyTodoList/**'
      - 'MainProject/MtdrSpring/backend/src/main/frontend/**'

# Permissions needed for the labeler to function properly
permissions:
  contents: read
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml
          sync-labels: true 