name: Linter Workflow

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'MainProject/MtdrSpring/backend/src/main/java/com/springboot/MyTodoList/**'
      - 'MainProject/MtdrSpring/backend/src/main/frontend/**'

jobs:
  lint:
    name: Run Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Super-Linter
        uses: github/super-linter@v6
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          FILTER_REGEX_INCLUDE: .*MainProject/MtdrSpring/backend/src/main/(java/com/springboot/MyTodoList|frontend)/.*
          JAVA_FILE_NAME: google_checks.xml

