name: Linter Workflow

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'MainProject/MtdrSpring/backend/src/main/java/com/springboot/MyTodoList/**'
      - 'MainProject/MtdrSpring/backend/src/main/frontend/**'

# Set specific permissions instead of implicit write-all
permissions:
  contents: read
  checks: write
  statuses: write
  security-events: write

jobs:
  lint:
    name: Run Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js for Frontend Linting
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: MainProject/MtdrSpring/backend/src/main/frontend/package-lock.json

      - name: Frontend Lint
        working-directory: MainProject/MtdrSpring/backend/src/main/frontend
        run: |
          npm ci
          npm run lint -- --max-warnings=100

      # Additional Java-specific linting step using Maven
      - name: Setup Java for Maven-based linting
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Java Checkstyle with Maven
        working-directory: MainProject/MtdrSpring/backend
        run: |
          chmod +x mvnw
          ./mvnw checkstyle:check

      - name: Run Super-Linter
        uses: github/super-linter@v6
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          FILTER_REGEX_INCLUDE: .*MainProject/MtdrSpring/backend/src/main/java/com/springboot/MyTodoList/.*
          JAVA_FILE_NAME: google_checks.xml
          # Only validate these languages - don't use mixed enable/disable approach
          VALIDATE_JAVA: true
          VALIDATE_GOOGLE_JAVA_FORMAT: true
          # Disable validation of all other linters by setting VALIDATE_ALL to false
          VALIDATE_ALL: false

